name: Python application

on:
  push:
    branches:
      - trigger_action_update_omim
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 9 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Update OMIM
      env:
        OMIM_KEY: ${{ secrets.OMIM_KEY }}
      run: |
        python3 update_omim.py --omim-key $OMIM_KEY --force
